routes/models/users.py
from db import get_db

def getUsers(user_id=None):
    """
    Model to get all or specific user/s.
    Args:
        user_id (int, optional): User ID to get. If not provided, gets all users.
    """
    try:
        # Create base query
        query = """
            SELECT
                a.pk_user_id,
                a.fk_employee_id,
                b.first_name,
                b.last_name,
                a.username,
                a.forgot_password,
                a.admin
            FROM Users a
            JOIN Employees b on a.fk_employee_id = b.pk_employee_id
        """
        values = ()

        if (user_id):
            # Add condition to base query if id is provided
            query += " WHERE pk_user_id = ?"
            values = (user_id,)
        
        # Execute the query
        db = get_db()
        users = db.execute(query, values).fetchall()

        # Convert result into a dictionary
        users = [dict(row) for row in users]

        return users
    except Exception as e:
        raise Exception(f"An error occurred: {e}")

def deleteUser(user_id=None):
    """
    Model to delete a specific user.
    Args:
        user_id (int): User ID to delete.
    """
    try:
        # Create base query
        query = """
            DELETE FROM Users
            WHERE pk_user_id = ?
        """
        values = (user_id,)
        
        # Execute the query
        db = get_db()
        db.execute("PRAGMA foreign_keys = ON") # Enable foreign keys for this connection

        db.execute(query, values)
        db.commit()

        return 'success'
    except Exception as e:
        raise Exception(f"An error occurred: {e}")

def changePassword(id, password):
    """
    Changes a users password. The route should be protected by an admin-only login.
    Args:
        id (int): The User ID of the password to change.
        password (str): A hashed password to change to.
    """
    try:
        query = """
            UPDATE Users
            SET 
                password = ?,
                forgot_password = 0
            WHERE pk_user_id = ?
        """
        values = (password, id)

        db = get_db()
        db.execute(query, values)
        db.commit()

        return 'success'
    except Exception as e:
        raise e

def changeUsername(id, username):
    """
    Changes a users username. The route should be protected by an admin-only login.
    Args:
        id (int): The User ID of the username to change.
        username (str): The new username to change to.
    """
    try:
        query = """
            UPDATE Users
            SET 
                username = ?
            WHERE pk_user_id = ?
        """
        values = (username, id)

        db = get_db()
        db.execute(query, values)
        db.commit()

        return 'success'
    except Exception as e:
        raise e

routes/auth.py
from flask import Blueprint, request, redirect, url_for, flash, render_template, abort
from flask_login import login_user, logout_user, login_required, current_user
from flask_bcrypt import Bcrypt

from functools import wraps

from .models.auth import LoginForm, RegisterForm, User
from .models.auth import usernameTaken, isEmployeeIdRegistered, registerUser, forgotPassword, getUserData, unForgotPassword
from .models.employees import get_employees

# Initialise blueprint and bcrypt
auth = Blueprint('auth', __name__)
bcrypt = Bcrypt()

# Custom decorator function to enforce admin permission on admin routes.
def admin_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if not current_user.admin:
            flash('You need to be an admin to access this page.', 'danger')
            return redirect(url_for('auth.dashboard'))
        return f(*args, **kwargs)
    return decorated_function

@auth.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm()
    if request.method == 'POST' and login_form.validate_on_submit():
        user = User.get(login_form.username.data)
        if user and bcrypt.check_password_hash(user.password, login_form.password.data):
            unForgotPassword(user.id)
            login_user(user)
            return redirect(url_for('auth.dashboard', active_page='dashboard'))
        
        flash('Either the username or password are incorrect. Please try again.', 'danger')
    return render_template('login.html', login_form=login_form)


@auth.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        employee_id = form.employee_id.data
        username = form.username.data
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')

        #Check if username already exists
        username_invalid = usernameTaken(username)
        if username_invalid:
            flash('Username already exists. Please pick a different username and try again.', 'danger')
            return render_template('register.html', register_form=form)
        
        #Check if employee_id is a valid id
        employee_id_valid = get_employees(employee_id)
        if not employee_id_valid:
            flash('Employee ID does not exist. Please ensure it is correct and try again. Otherwise, please ask an admin to add you to the system.', 'danger')
            return render_template('register.html', register_form=form)
        
        #Check if employee_id is already registered
        user_id_invalid = isEmployeeIdRegistered(employee_id)
        if user_id_invalid:
            flash('Employee ID is already registered to a username. Please ensure it is correct and try again.', 'danger')
            return render_template('register.html', register_form=form)


        # Register user
        data = {
            'employee_id': employee_id,
            'username': username,
            'hashed_password': hashed_password
        }
        status = registerUser(data)

        if status['message'] == 'success':
            flash('Registration Successful! You may now log in.', 'success')
            return redirect(url_for('auth.login'))
    return render_template('register.html', register_form=form)


@auth.route('/forgot_password/<user_id>', methods=['POST'])
def forgot_password(user_id):
    if request.method == 'POST':
        status = forgotPassword(user_id)
        if status == 'success':
            flash('Request to reset password sent. Please inform an admin member to approve this request.', 'success')
            return {'status': 'success'}
        return {'status': 'error'}


@auth.route('/check_users/<username>', methods=['GET'])
def check_users(username):
    if request.method == 'GET':
        user = getUserData(username)
        if user:
            return {'user_id': user['pk_user_id']}
        return {'user_id': ''}


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'success')
    return redirect(url_for('auth.login'))


@auth.route('/dashboard')
@login_required
def dashboard():
    return render_template('dashboard.html', active_page='dashboard')

routes/employees.py
from flask import request, jsonify, Blueprint, render_template, flash, redirect, url_for
from flask_login import login_required, current_user

from .models.employees import add_employee, get_employees, update_employee, delete_employee
from .auth import admin_required

employees = Blueprint('employees', __name__)

@employees.route('/')
@login_required
def index():
    return render_template('employees-view.html', active_page='view_records')

@employees.route('/modify')
@login_required
@admin_required
def modify_index():
    return render_template('employees-modify.html', active_page='modify_records')

@employees.route('/get_employees', methods=['GET'])
@employees.route('/get_employees/<int:employee_id>', methods=['GET'])
@login_required
def get_employees_route(employee_id=None):
    """
    Route to get all or specific employee/s. <br>
    If route is requested by a non-admin account, only the requesting users details are ever returned.
    Args:
        employee_id (int, optional): Employee ID to get. If not provided, gets all employees.
    """
    if request.method == 'GET':
        if current_user.admin:
            employees_data = get_employees(employee_id)
        else:
            employees_data = get_employees(current_user.employee_id)
        
        if employees_data:
            return jsonify(employees_data), 200
        else:
            return jsonify({"error": "No employees found"})


@employees.route('/add_employee', methods=['POST'])
@login_required
@admin_required
def add_employee_route():
    """
    Route to add a new employee.
    Args:
        None (expects JSON payload in request body):
            - first_name (str): The employee's first name.
            - last_name (str): The employee's last name.
            - employee_position (str): The employee's position.
            - default_leave_balance (float/int): The base leave balance for the employee.
            - default_sick_leave_balance (float/int): The base sick leave balance for the employee.
    """
    if request.method == 'POST':
        employee_data = request.get_json()
        first_name = employee_data.get('first_name')
        last_name = employee_data.get('last_name')
        position = employee_data.get('employee_position')
        default_leave_balance = employee_data.get('default_leave_balance')
        default_sick_leave_balance = employee_data.get('default_sick_leave_balance')


        if not first_name or not last_name or not position or not default_leave_balance or not default_sick_leave_balance:
            return jsonify({"error": "Missing required fields"}), 400
        
        try: 
            status = add_employee(employee_data)
            if status['status'] == 'success':
                return jsonify({"message": "Employee added successfully", 'employee_id': status['employee_id']}), 201
            else:
                return jsonify({"error": "Failed to add employee"}), 500
        except Exception as e:
            return jsonify({"error": str(e)}), 500

@employees.route('/update_employee/<int:employee_id>', methods=['PUT'])
@login_required
@admin_required
def update_employee_route(employee_id):
    """
    Route to update an existing employee.
    Args:
        employee_id (int): Employee ID to update.
    """
    if request.method == 'PUT':
        employee_data = request.get_json()
        try:
            status = update_employee(employee_id, employee_data)
            if status == 'success':
                return jsonify({"message": "Employee updated successfully"}), 200
            else:
                return jsonify({"error": "Failed to update employee"}), 500
        except Exception as e:
            return jsonify({"error": str(e)}), 500

@employees.route('/delete_employee/<int:employee_id>', methods=['DELETE'])
@login_required
@admin_required
def delete_employee_route(employee_id):
    """
    Route to delete an employee.
    Args:
        employee_id (int): Employee ID to delete.
    """
    if request.method == 'DELETE':
        try:
            status = delete_employee(employee_id)
            if status == 'success':
                return jsonify({"message": "Employee deleted successfully"}), 200
            else:
                return jsonify({"error": "Failed to delete employee"}), 500
        except Exception as e:
            return jsonify({"error": str(e)}), 500

routes/users.py
from flask import request, jsonify, Blueprint, render_template
from flask_login import login_required, current_user
from flask_bcrypt import Bcrypt

from .models.users import getUsers, deleteUser, changePassword, changeUsername
from .models.auth import isEmployeeIdRegistered, usernameTaken, registerUser, upgradeUser, demoteUser
from .auth import admin_required

users = Blueprint('users', __name__)
bcrypt = Bcrypt()

@users.route('/')
@login_required
def index():
    return render_template('users.html', active_page='modify_login')

@users.route('/get_users', methods=['GET'])
@users.route('/get_users/<int:user_id>', methods=['GET'])
@login_required
def getEmployeesRoute(user_id=None):
    """
    Route to get all or specific user/s.
    Args:
        user_id (int, optional): User ID to get. If not provided, gets all users.
    """
    if request.method == 'GET':
        if current_user.admin:
            users = getUsers(user_id)
        else:
            users = getUsers(current_user.id)
        
        if users:
            return jsonify(users), 200
        else:
            return jsonify({"error": "No employees found"}), 404

@users.route('/get_users/is_registered/<int:employee_id>', methods=['GET'])
def getIsRegisteredRoute(employee_id):
    """
    Route to check if an employee id is already registered.
    Args:
        user_id (int): User ID to check.
    """
    if request.method == 'GET':
        registered = isEmployeeIdRegistered(employee_id)
        return jsonify({'registered': registered})

@users.route('/get_users/username_taken', methods=['GET'])
def getUsernameTakenRoute():
    """
    Route to check if a username is already registered.
    Args:
        username (str): Username to check.
    """
    if request.method == 'GET':
        username = request.args.get('username')
        taken = usernameTaken(username)
        return jsonify({'registered': taken})
    
@users.route('/add_user', methods=['POST'])
@login_required
@admin_required
def addUser():
    """
    Route to add a user from the modify login page
    """
    args = request.get_json()
    if (args):
        employee_id = args['employee_id']
        username = args['username']
        admin = args['admin']
        hashed_password = bcrypt.generate_password_hash(args['password']).decode('utf-8')

        register = registerUser({
            'employee_id': employee_id,
            'username': username,
            'hashed_password': hashed_password
        })

        user_id = register['pk_user_id']
        if admin == True:
            upgradeUser(user_id)
        
        if register['message'] == 'success':
            return jsonify({'message': 'success'})
        return jsonify({'message': 'error'})

@users.route('/promote_user/<int:user_id>', methods=['PUT'])
@login_required
@admin_required
def promoteUserRoute(user_id):
    """
    Route to promote a user from the modify login page
    """
    if request.method == 'PUT':
        upgrade = upgradeUser(user_id)
        if upgrade == 'success':
            return {'message': 'success'}
        else:
            return {'message': 'error'}
        
@users.route('/demote_user/<int:user_id>', methods=['PUT'])
@login_required
@admin_required
def demoteUserRoute(user_id):
    """
    Route to demote a user from the modify login page
    """
    if request.method == 'PUT':
        demote = demoteUser(user_id)
        if demote == 'success':
            return {'message': 'success'}
        else:
            return {'message': 'error'}

@users.route('/delete_user/<int:user_id>', methods=['DELETE'])
@login_required
@admin_required
def deleteUserRoute(user_id):
    """
    Route to delete a user from the modify login page
    """
    if request.method == 'DELETE':
        delete = deleteUser(user_id)
        if delete == 'success':
            return {'message': 'success'}
        else:
            return {'message': 'error'}

@users.route('/change_password/<int:user_id>', methods=['PUT'])
@login_required
def changePasswordRoute(user_id):
    """
    Route to change a user password from the modify login page
    """
    if request.method == 'PUT':
        data = request.get_json()
        hashed_password = bcrypt.generate_password_hash(data['password']).decode('utf-8')
        change = changePassword(user_id, hashed_password)
        if change == 'success':
            return {'message': 'success'}
        else:
            return {'message': 'error'}

@users.route('/change_username/<int:user_id>', methods=['PUT'])
@login_required
def changeUsernameRoute(user_id):
    """
    Route to change a username from the modify login page
    """
    if request.method == 'PUT':
        data = request.get_json()
        username = data['username']

        change = changeUsername(user_id, username)
        if change == 'success':
            return {'message': 'success'}
        else:
            return {'message': 'error'}

templates/base.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@500&display=swap" rel="stylesheet">
    
    <!-- Base.css -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">

    
    <title>NM EMS | {% block title %}{% endblock %}</title>
</head>
<body>
    <div class="loader-backdrop" id="spinnerLoader">
        <div class="spinner-border" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
    </div>

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('auth.dashboard') }}">NM</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link {% if active_page == 'dashboard'%}active{% endif %}" aria-current="page" href="{{ url_for('auth.dashboard') }}">Home</a>
                    {% if current_user.admin %}
                    <a class="nav-link {% if active_page == 'view_records'%}active{% endif %}" href="{{ url_for('employees.index') }}">View Records</a>
                    <a class="nav-link {% if active_page == 'modify_records'%}active{% endif %}" href="{{ url_for('employees.modify_index') }}">Modify Records</a>
                    <a class="nav-link {% if active_page == 'process_leave'%}active{% endif %}" href="{{ url_for('leave.index') }}">Process Leave</a>
                    <a class="nav-link {% if active_page == 'modify_login'%}active{% endif %}" href="{{ url_for('users.index') }}">Modify Login Accounts</a>
                    {% else %}
                    <a class="nav-link {% if active_page == 'view_records'%}active{% endif %}" href="{{ url_for('employees.index') }}">View Record</a>
                    <a class="nav-link {% if active_page == 'process_leave'%}active{% endif %}" href="{{ url_for('leave.index') }}">Request Leave</a>
                    <a class="nav-link {% if active_page == 'modify_login'%}active{% endif %}" href="{{ url_for('users.index') }}">Modify Details</a>
                    {% endif %}
                </div>
            </div>
            <div class="d-flex align-items-center">
                <!-- Session Management -->
                <span class="username-text">{{ current_user.username }}</span>
                <div class="dropstart">
                    <a class="d-flex align-items-center mx-3 user-icon" role="button" data-bs-toggle="dropdown" href="#" aria-expanded="false">
                        {% if current_user.admin %}
                        <i class="fas fa-user-tie"></i>
                        {% else %}
                        <i class="fas fa-user"></i>
                        {% endif %}
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{{ url_for('auth.logout') }}">Logout</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>

    <!-- Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/fa4c14ad6c.js" crossorigin="anonymous"></script>
    <!-- jQuery -->    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

    <!-- Dynamic Flash Message Container -->
    <div id="flash-container"></div>

    <!-- Flash Messages from backend -->
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    <script>
        const current_user = {
            id: "{{ current_user.id }}",
            employee_id: "{{ current_user.employee_id }}",
            username: "{{ current_user.username }}",
            admin: "{{ current_user.admin }}"
        }
    </script>

    <div class="container">
        {% block content %}
        <!-- Content will be inserted here -->
        {% endblock %}
    </div>
    
    
</body>
</html>

templates/dashboard.html
{% extends "base.html" %}
{% block title %} Dashboard {% endblock %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/dashboard.css') }}">

<div class="row mt-3">
    {% if current_user.admin %}
    <div class="col-6">
    {% else %}
    <div class="col-12">
    {% endif %}
        <div class="card" href="{{ url_for('employees.index') }}">
            <div class="card-body">
                <i class="fas fa-clipboard fa-2xl position-absolute top-0 end-0 m-4 pt-2"></i>
                <h5 class="card-title">View Records</h5>
                {% if current_user.admin %}
                <h6 class="card-subtitle mb-2">View all employee records.</h6>
                {% else %}
                <h6 class="card-subtitle mb-2">View your employee record.</h6>
                {% endif %}
                <hr>
                {% if current_user.admin %}
                <p class="card-text">
                    As an admin, you can view all employee records including personal details, performance statistics, leave balances, and more.<br>
                    Performance and attendance evaluations are also accessible, allowing you to monitor employee progress and contributions effectively.
                </p>
                {% else %}
                <p class="card-text">
                    View all your employee records including personal details, performance statistics, leave balances, and more.
                </p>
                {% endif %}
            </div>
        </div>
    </div>
    {% if current_user.admin %}
    <div class="col-6">
        <div class="card" href="{{ url_for('employees.modify_index') }}">
            <div class="card-body">
                <i class="fas fa-pen-to-square fa-2xl position-absolute top-0 end-0 m-4 pt-2"></i>
                <h5 class="card-title">Modify Records</h5>
                <h6 class="card-subtitle mb-2">Modify records of select employees.</h6>
                <hr>
                <p class="card-text">
                    Admins can modify employee records, including personal details, performance statistics, and leave balances.<br>
                    This feature also allows you to add or delete employee records as necessary.
                </p>
            </div>
        </div>
    </div>
    {% endif %}
</div>
<div class="row mt-3">
    <div class="col-6">
        <div class="card" href="{{ url_for('leave.index') }}">
            <div class="card-body">
                <i class="fas fa-calendar-days fa-2xl position-absolute top-0 end-0 m-4 pt-2"></i>
                {% if current_user.admin %}
                <h5 class="card-title">Process Leave</h5>
                <h6 class="card-subtitle mb-2">Process any active leave requests.</h6>
                {% else %}
                <h5 class="card-title">Manage Leave</h5>
                <h6 class="card-subtitle mb-2">View or create new leave requests.</h6>
                {% endif %}
                <hr>
                {% if current_user.admin %}
                <p class="card-text">
                    As an admin you can process leave requests from employees, including approving or rejecting leave applications.<br>
                    You can also view the status of all leave requests, ensuring that employee leave is managed efficiently and transparently.
                </p>
                {% else %}
                <p class="card-text">
                    View your leave balance, submit new leave requests, and track the status of your applications.<br>
                    Easily manage your time off and stay informed about your leave history.
                </p>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-6">
        <div class="card" href="{{ url_for('users.index') }}">
            <div class="card-body">
                <i class="fas fa-users fa-2xl position-absolute top-0 end-0 m-4 pt-2"></i>
                {% if current_user.admin %}
                <h5 class="card-title">Modify Login Accounts</h5>
                <h6 class="card-subtitle mb-2">Amend employee account login details.</h6>
                {% else %}
                <h5 class="card-title">Change Login Account Details</h5>
                <h6 class="card-subtitle mb-2">Amend account login details.</h6>
                {% endif %}
                <hr>
                {% if current_user.admin %}
                <p class="card-text">
                    As an admin, you can modify employee login accounts, including resetting passwords and updating usernames.<br>
                    You can also create new accounts, reset forgotten passwords, and upgrade accounts to admin status if necessary.<br>
                    This feature ensures that employee access to the system is secure and up-to-date.
                </p>
                {% else %}
                <p class="card-text">
                    View and update your account details, such as your username and password. <br>Keep your login information secure and up to date.
                </p>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $('.card').on('click', function(){
            window.location.href = $(this).attr('href');
        });
    });
</script>

{% endblock %}

templates/login.html
{% extends "base-auth.html" %}
{% block title %}Login{% endblock %}

{% block content %}
<!-- Forgot Password Modal -->
<div class="modal fade" id="forgot_password_modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Forgot Password?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <label for="username" class="form-label">Username:</label>
                    <input class="form-control" id="username" value="">
                    <div class="invalid-feedback">
                        Username does not exist. Please ensure it is typed correctly.
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary btn-sm disabled" id="send_request_btn">Send Request</button>
            </div>
        </div>
    </div>
</div>


<!-- Main Login Prompt -->
<div class="container square-box">
    <h1 class="text-center">Login</h1>
    <form method="POST">
        {{ login_form.hidden_tag() }} <!-- CSRF Token -->
        <div class="mb-3">
            {{ login_form.username.label(class="form-label") }}
            {{ login_form.username(class="form-control") }}
        </div>
        <div class="mb-3">
            {{ login_form.password.label(class="form-label") }}
            {{ login_form.password(class="form-control") }}
            <a id="forgot_password" class="small" href="#">Forgot Password?</a>
        </div>
        <div class="d-flex justify-content-end">
            <a class="btn btn-secondary btn-sm mx-2" role="button" href="{{ url_for('auth.register') }}">Register</a>
            {{ login_form.submit(class="btn btn-primary btn-sm") }}
        </div>
    </form>
</div>

<script>
    $('#forgot_password').on('click', function() {
        $('#forgot_password_modal').modal('toggle');
    })

    $('#username').on('input', function(){
        const send_request = $('#send_request_btn');
        if ($(this).val().length > 0){
            send_request.removeClass('disabled')
        } else {
            send_request.addClass('disabled')
        };
    });

    $('#send_request_btn').on('click', function(){
        const username = $('#username').val();
        if (!username) return;

        $.ajax({
            type: "GET",
            url: `/check_users/${username}`,
            success: function(resp){
                const user_id = resp['user_id'];
                if (!user_id) {
                    toggleInvalidUsername(false);
                    return
                }

                toggleInvalidUsername(true);
                reset_password(user_id);
            },
            error: function(xhr, ajaxOptions, error){
                console.error(xhr)
                console.error(error)
            }  
        })
    });

    function toggleInvalidUsername(valid=false){
        const element = $('#username');
        const hasInvalid = element.hasClass('is-invalid');

        if (!valid && !hasInvalid) element.addClass('is-invalid')
        else if (valid && hasInvalid) element.removeClass('is-invalid')
    }

    function reset_password(user_id){
        $.ajax({
            type: "POST",
            url: `/forgot_password/${user_id}`,
            success: function(resp){
                if (resp['status'] === 'success'){
                    location.reload();
                }
            },
            error: function(xhr, ajaxOptions, error){
                console.error(xhr)
                console.error(error)
            }
        })
    }
</script> 
{% endblock %}